version: "3.8"
services:
  db:
    image: mysql:8.0-debian
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: myrootpassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ./.env
    depends_on:
      - db

volumes:
  mysql_data:
